# Generated by Django 4.1.7 on 2023-04-20 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentbid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentlist', models.IntegerField(default=0)),
                ('commentowner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=64)),
                ('discription', models.TextField(default=None)),
                ('url', models.URLField(default=None)),
                ('startbid', models.IntegerField(default=0)),
                ('category', models.CharField(default=None, max_length=64)),
                ('maxbid', models.IntegerField(default=0)),
                ('Listingowner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('maxbidonwer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
