# Generated by Django 4.1.7 on 2023-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
